/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowInscription (void)
{
  GtkWidget *windowInscription;
  GtkWidget *fixed1;
  GtkWidget *entryNom;
  GtkWidget *entryRole;
  GtkWidget *entryPassword;
  GtkWidget *entryUsername;
  GtkWidget *entryPrenom;
  GtkWidget *label1;
  GtkWidget *labelNom;
  GtkWidget *labelPrenom;
  GtkWidget *labelUsername;
  GtkWidget *labelPassword;
  GtkWidget *labelRole;
  GtkWidget *buttonAjouter;

  windowInscription = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowInscription), _("Inscription"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (windowInscription), fixed1);

  entryNom = gtk_entry_new ();
  gtk_widget_show (entryNom);
  gtk_fixed_put (GTK_FIXED (fixed1), entryNom, 80, 64);
  gtk_widget_set_size_request (entryNom, 232, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNom), 8226);

  entryRole = gtk_entry_new ();
  gtk_widget_show (entryRole);
  gtk_fixed_put (GTK_FIXED (fixed1), entryRole, 80, 264);
  gtk_widget_set_size_request (entryRole, 232, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryRole), 8226);

  entryPassword = gtk_entry_new ();
  gtk_widget_show (entryPassword);
  gtk_fixed_put (GTK_FIXED (fixed1), entryPassword, 80, 216);
  gtk_widget_set_size_request (entryPassword, 232, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPassword), 8226);

  entryUsername = gtk_entry_new ();
  gtk_widget_show (entryUsername);
  gtk_fixed_put (GTK_FIXED (fixed1), entryUsername, 80, 168);
  gtk_widget_set_size_request (entryUsername, 232, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryUsername), 8226);

  entryPrenom = gtk_entry_new ();
  gtk_widget_show (entryPrenom);
  gtk_fixed_put (GTK_FIXED (fixed1), entryPrenom, 80, 120);
  gtk_widget_set_size_request (entryPrenom, 232, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPrenom), 8226);

  label1 = gtk_label_new (_("Inscription"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 128, 8);
  gtk_widget_set_size_request (label1, 128, 40);

  labelNom = gtk_label_new (_("Nom : "));
  gtk_widget_show (labelNom);
  gtk_fixed_put (GTK_FIXED (fixed1), labelNom, 0, 64);
  gtk_widget_set_size_request (labelNom, 72, 32);

  labelPrenom = gtk_label_new (_("Prenom : "));
  gtk_widget_show (labelPrenom);
  gtk_fixed_put (GTK_FIXED (fixed1), labelPrenom, 0, 120);
  gtk_widget_set_size_request (labelPrenom, 72, 32);

  labelUsername = gtk_label_new (_("Username : "));
  gtk_widget_show (labelUsername);
  gtk_fixed_put (GTK_FIXED (fixed1), labelUsername, 0, 168);
  gtk_widget_set_size_request (labelUsername, 80, 32);

  labelPassword = gtk_label_new (_("Password : "));
  gtk_widget_show (labelPassword);
  gtk_fixed_put (GTK_FIXED (fixed1), labelPassword, 0, 216);
  gtk_widget_set_size_request (labelPassword, 72, 32);

  labelRole = gtk_label_new (_("Role : "));
  gtk_widget_show (labelRole);
  gtk_fixed_put (GTK_FIXED (fixed1), labelRole, 0, 264);
  gtk_widget_set_size_request (labelRole, 72, 32);

  buttonAjouter = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (buttonAjouter);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonAjouter, 144, 312);
  gtk_widget_set_size_request (buttonAjouter, 80, 48);

  g_signal_connect ((gpointer) buttonAjouter, "clicked",
                    G_CALLBACK (on_buttonAjouter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowInscription, windowInscription, "windowInscription");
  GLADE_HOOKUP_OBJECT (windowInscription, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (windowInscription, entryNom, "entryNom");
  GLADE_HOOKUP_OBJECT (windowInscription, entryRole, "entryRole");
  GLADE_HOOKUP_OBJECT (windowInscription, entryPassword, "entryPassword");
  GLADE_HOOKUP_OBJECT (windowInscription, entryUsername, "entryUsername");
  GLADE_HOOKUP_OBJECT (windowInscription, entryPrenom, "entryPrenom");
  GLADE_HOOKUP_OBJECT (windowInscription, label1, "label1");
  GLADE_HOOKUP_OBJECT (windowInscription, labelNom, "labelNom");
  GLADE_HOOKUP_OBJECT (windowInscription, labelPrenom, "labelPrenom");
  GLADE_HOOKUP_OBJECT (windowInscription, labelUsername, "labelUsername");
  GLADE_HOOKUP_OBJECT (windowInscription, labelPassword, "labelPassword");
  GLADE_HOOKUP_OBJECT (windowInscription, labelRole, "labelRole");
  GLADE_HOOKUP_OBJECT (windowInscription, buttonAjouter, "buttonAjouter");

  return windowInscription;
}

GtkWidget*
create_windowAuthentification (void)
{
  GtkWidget *windowAuthentification;
  GtkWidget *fixed2;
  GtkWidget *entryUsername;
  GtkWidget *entryPassword;
  GtkWidget *labelUsername;
  GtkWidget *labelPassword;
  GtkWidget *buttonLogin;

  windowAuthentification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowAuthentification), _("Authentification"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (windowAuthentification), fixed2);

  entryUsername = gtk_entry_new ();
  gtk_widget_show (entryUsername);
  gtk_fixed_put (GTK_FIXED (fixed2), entryUsername, 136, 80);
  gtk_widget_set_size_request (entryUsername, 224, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryUsername), 8226);

  entryPassword = gtk_entry_new ();
  gtk_widget_show (entryPassword);
  gtk_fixed_put (GTK_FIXED (fixed2), entryPassword, 136, 144);
  gtk_widget_set_size_request (entryPassword, 224, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPassword), 8226);

  labelUsername = gtk_label_new (_("Username : "));
  gtk_widget_show (labelUsername);
  gtk_fixed_put (GTK_FIXED (fixed2), labelUsername, 32, 72);
  gtk_widget_set_size_request (labelUsername, 104, 48);

  labelPassword = gtk_label_new (_("Password : "));
  gtk_widget_show (labelPassword);
  gtk_fixed_put (GTK_FIXED (fixed2), labelPassword, 32, 136);
  gtk_widget_set_size_request (labelPassword, 96, 48);

  buttonLogin = gtk_button_new_with_mnemonic (_("Login"));
  gtk_widget_show (buttonLogin);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonLogin, 176, 208);
  gtk_widget_set_size_request (buttonLogin, 112, 48);

  g_signal_connect ((gpointer) buttonLogin, "clicked",
                    G_CALLBACK (on_buttonLogin_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowAuthentification, windowAuthentification, "windowAuthentification");
  GLADE_HOOKUP_OBJECT (windowAuthentification, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (windowAuthentification, entryUsername, "entryUsername");
  GLADE_HOOKUP_OBJECT (windowAuthentification, entryPassword, "entryPassword");
  GLADE_HOOKUP_OBJECT (windowAuthentification, labelUsername, "labelUsername");
  GLADE_HOOKUP_OBJECT (windowAuthentification, labelPassword, "labelPassword");
  GLADE_HOOKUP_OBJECT (windowAuthentification, buttonLogin, "buttonLogin");

  return windowAuthentification;
}

GtkWidget*
create_windowAdmin (void)
{
  GtkWidget *windowAdmin;
  GtkWidget *fixed3;
  GtkWidget *labelHello;

  windowAdmin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowAdmin), _("Espace Admin"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (windowAdmin), fixed3);

  labelHello = gtk_label_new (_("Bienvenue \303\240 l'espace ADMIN"));
  gtk_widget_show (labelHello);
  gtk_fixed_put (GTK_FIXED (fixed3), labelHello, 72, 64);
  gtk_widget_set_size_request (labelHello, 272, 144);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowAdmin, windowAdmin, "windowAdmin");
  GLADE_HOOKUP_OBJECT (windowAdmin, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (windowAdmin, labelHello, "labelHello");

  return windowAdmin;
}

