/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowgestion (void);
GtkWidget* create_windowajouter (void);
GtkWidget* create_windowmodifier (void);
GtkWidget* create_windowsupprimer (void);
GtkWidget* create_windowservices (void);
GtkWidget* create_windowlistclient (void);
GtkWidget* create_windowachats (void);
GtkWidget* create_windowmodifierc (void);
GtkWidget* create_windowerreur (void);
GtkWidget* create_dialog1client (void);
GtkWidget* create_dialog2client (void);
GtkWidget* create_window_liste_achat (void);
GtkWidget* create_window_reservation (void);
GtkWidget* create_windowliste_reservation (void);
GtkWidget* create_dialogsupprimer (void);
GtkWidget* create_windowmeilleur_client (void);
