/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *windowgestion;
  GtkWidget *windowajouter;
  GtkWidget *windowmodifier;
  GtkWidget *windowsupprimer;
  GtkWidget *windowservices;
  GtkWidget *windowlistclient;
  GtkWidget *windowachats;
  GtkWidget *windowfacture;
  GtkWidget *windowmodifierc;
   GtkWidget *windowerreur;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  windowgestion = create_windowgestion ();
  gtk_widget_show (windowgestion);
 /* windowajouter = create_windowajouter ();
  gtk_widget_show (windowajouter);
  windowmodifier = create_windowmodifier ();
  gtk_widget_show (windowmodifier);
  windowsupprimer = create_windowsupprimer ();
  gtk_widget_show (windowsupprimer);
  windowservices = create_windowservices ();
  gtk_widget_show (windowservices);
  windowlistclient = create_windowlistclient ();
  gtk_widget_show (windowlistclient);
  windowachats = create_windowachats ();
  gtk_widget_show (windowachats);
  windowfacture = create_windowfacture ();
  gtk_widget_show (windowfacture);
  windowmodifierc = create_windowmodifierc ();
  gtk_widget_show (windowmodifierc);
  windowerreur = create_windowerreur ();
  gtk_widget_show (windowerreur);*/

  gtk_main ();
  return 0;
}

