/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *windowGestionEmployes;
  GtkWidget *windowAjoutEmploye;
  GtkWidget *windowModifierEmploye;
  GtkWidget *windowSupprimerEmploye;
  GtkWidget *windowListeEmployes;
  GtkWidget *windowModification;
  GtkWidget *windowHome;
  GtkWidget *windowLogin;
  GtkWidget *windowGestionCapteurs;
  GtkWidget *windowAjoutCapteur;
  GtkWidget *windowModifierCapteur;
  GtkWidget *windowSupprimeCapteur;
  GtkWidget *windowListeCapteurs;
  GtkWidget *ModifierCapteur;
  GtkWidget *windowAlarmants;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory("../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  windowLogin = create_windowLogin();
  gtk_widget_show(windowLogin);
  /*windowGestionEmployes = create_windowGestionEmployes ();
  gtk_widget_show (windowGestionEmployes);
  windowHome = create_windowHome();
  gtk_widget_show(windowHome);*/
  /*windowAjoutEmploye = create_windowAjoutEmploye ();
  gtk_widget_show (windowAjoutEmploye);
  windowModifierEmploye = create_windowModifierEmploye ();
  gtk_widget_show (windowModifierEmploye);
  windowSupprimerEmploye = create_windowSupprimerEmploye ();
  gtk_widget_show (windowSupprimerEmploye);
  windowListeEmployes = create_ModifierEmploye ();
  gtk_widget_show (windowListeEmployes);
  windowModification = create_ModifierEmploye();
  gtk_widget_show(windowModification);
  
  windowGestionCapteurs = create_windowGestionCapteurs ();
  gtk_widget_show (windowGestionCapteurs);
  
  windowAjoutCapteur = create_windowAjoutCapteur ();
  gtk_widget_show (windowAjoutCapteur);
  windowModifierCapteur = create_windowModifierCapteur ();
  gtk_widget_show (windowModifierCapteur);
  windowSupprimeCapteur = create_windowSupprimeCapteur ();
  gtk_widget_show (windowSupprimeCapteur);
  windowListeCapteurs = create_windowListeCapteurs ();
  gtk_widget_show (windowListeCapteurs);
  ModifierCapteur = create_ModifierCapteur ();
  gtk_widget_show (ModifierCapteur);
  
  windowAlarmants = create_windowAlarmants ();
  gtk_widget_show (windowAlarmants);
  */
  gtk_main ();
  return 0;
}

