/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowGestionCapteurs (void);
GtkWidget* create_windowAjoutCapteur (void);
GtkWidget* create_windowModifierCapteur (void);
GtkWidget* create_windowSupprimeCapteur (void);
GtkWidget* create_windowListeCapteurs (void);
GtkWidget* create_ModifierCapteur (void);
GtkWidget* create_dialog1 (void);
GtkWidget* create_dialog2 (void);
GtkWidget* create_dialog3 (void);
GtkWidget* create_windowRemplir (void);
GtkWidget* create_window1 (void);
