/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *windowGestionCapteurs;
  GtkWidget *windowAjoutCapteur;
  GtkWidget *windowModifierCapteur;
  GtkWidget *windowSupprimeCapteur;
  GtkWidget *windowListeCapteurs;
  GtkWidget *ModifierCapteur;
GtkWidget *window1;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  windowGestionCapteurs = create_windowGestionCapteurs ();
  gtk_widget_show (windowGestionCapteurs);
  /*windowAjoutCapteur = create_windowAjoutCapteur ();
  gtk_widget_show (windowAjoutCapteur);
  windowModifierCapteur = create_windowModifierCapteur ();
  gtk_widget_show (windowModifierCapteur);
  windowSupprimeCapteur = create_windowSupprimeCapteur ();
  gtk_widget_show (windowSupprimeCapteur);
  windowListeCapteurs = create_windowListeCapteurs ();
  gtk_widget_show (windowListeCapteurs);
  ModifierCapteur = create_ModifierCapteur ();
  gtk_widget_show (ModifierCapteur);

  window1 = create_window1 ();
  gtk_widget_show (window1);
*/
  gtk_main ();
  return 0;
}

